let checkoutSong=null,checkoutOrder=null;
async function shopApi(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||'Please try again.');return data;}
function openNameRequest(name=''){$('name-request-form').reset();$('requested-name').value=name;$('request-heading').textContent=name?`No song for ${name} yet`:'Request your name song';$('request-message').textContent='';$('name-request').showModal();}
$('cancel-name-request').onclick=()=>$('name-request').close();
$('name-request-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const r=await shopApi('/api/requests',{name:$('requested-name').value,email:$('requested-email').value,website:$('request-website').value,consent:$('request-consent').checked});$('request-message').textContent=r.message;$('name-request-form').reset();}catch(e){$('request-message').textContent=e.message;}finally{b.disabled=false;}};
function openCheckout(song=null){checkoutSong=song;$('checkout-form').reset();$('checkout-form').classList.remove('hidden');$('reference-form').classList.add('hidden');$('checkout-message').textContent='';$('checkout-title').textContent=song?'Buy '+song.title:'MQ3 membership';const m=window.mq3Catalog?.membership;$('checkout-description').textContent=song?`₱${(song.price/100).toFixed(2)} — full access to this song.`:m?`₱${(m.price/100).toFixed(2)} — ${m.days} days of access to published songs. No automatic renewal.`:'Membership setup is not available yet.';for(const o of $('payment-provider').options)o.disabled=!window.mq3Catalog?.payments?.[o.value];const available=[...$('payment-provider').options].find(o=>!o.disabled);if(available)$('payment-provider').value=available.value;else $('checkout-message').textContent='Payment methods are not connected yet.';$('checkout').showModal();}
$('membership').onclick=()=>openCheckout();$('close-checkout').onclick=$('close-reference').onclick=()=>$('checkout').close();
function paymentInstructions(order){checkoutOrder=order.id;$('checkout-form').classList.add('hidden');$('reference-form').classList.remove('hidden');$('reference-message').textContent='';$('payment-reference').value='';const target=$('payment-instructions');target.replaceChildren(node('p',`Order ${order.id}`),node('p',`Pay ₱${(order.amount/100).toFixed(2)} PHP. Include your order ID if the payment app supports a note.`));if(order.instructions.number)target.append(node('p',`GCash: ${order.instructions.number} · ${order.instructions.account}`));if(order.instructions.url){const link=node('a','Open PayPal payment page','button');link.href=order.instructions.url;link.target='_blank';link.rel='noopener noreferrer';target.append(link);}target.append(node('p','Return here and enter the transaction reference. MQ3 will verify the payment before enabling access.'));}
$('checkout-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{paymentInstructions(await shopApi('/api/orders',{kind:checkoutSong?'song':'membership',songId:checkoutSong?.id,email:$('buyer-email').value,provider:$('payment-provider').value}));}catch(e){$('checkout-message').textContent=e.message;}finally{b.disabled=false;}};
$('reference-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await shopApi(`/api/orders/${checkoutOrder}/reference`,{reference:$('payment-reference').value});$('reference-message').textContent='Submitted. Check My purchases for verification status. Keep your payment receipt.';}catch(e){$('reference-message').textContent=e.message;}finally{b.disabled=false;}};
async function purchases(){const list=$('purchase-list');list.textContent='Loading…';try{const orders=await shopApi('/api/my-orders');list.replaceChildren();if(!orders.length)list.append(node('p','No orders in this browser yet.'));orders.forEach(o=>{const item=node('div');item.append(node('p',`${o.kind==='membership'?'Membership':tracks.find(t=>t.id===o.song_id)?.title||'Song'} · ₱${(o.amount/100).toFixed(2)} · ${o.status}`));if(o.expires_at)item.append(node('p','Access until '+new Date(o.expires_at).toLocaleString()));if(['pending','submitted'].includes(o.status)){const b=node('button','Payment details','button');b.onclick=async()=>{try{const order=await shopApi('/api/orders/'+o.id);$('purchases').close();$('checkout').showModal();paymentInstructions(order);}catch(e){toast(e.message);}};item.append(b);}list.append(item);});}catch(e){list.textContent=e.message;}}
$('my-purchases').onclick=()=>{$('purchases').showModal();purchases();};$('refresh-purchases').onclick=purchases;$('close-purchases').onclick=()=>$('purchases').close();
