import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {createApp} from '../src/index.js';
import {passwordHash} from '../src/security.js';
const require=createRequire(import.meta.url);const {PGlite}=require(process.env.MQ3_PGLITE_MODULE);
test('credit-load delete/restore preserves payment, wallet and ledger; approved loads remain in API',async t=>{
 const db=new PGlite();t.after(()=>db.close());await db.exec(await readFile(new URL('../schema.sql',import.meta.url),'utf8'));
 await db.exec(`CREATE TABLE users(id uuid PRIMARY KEY,email text,display_name text);
 CREATE TABLE wallets(user_id uuid PRIMARY KEY,purchased_credits integer DEFAULT 0,updated_at timestamptz);
 CREATE TABLE credit_load_orders(id uuid PRIMARY KEY,user_id uuid,amount_pesos integer,credits integer,payment_provider text,payment_reference text,status text,created_at timestamptz DEFAULT now(),reviewed_at timestamptz);
 CREATE TABLE credit_transactions(id uuid PRIMARY KEY,user_id uuid,transaction_type text,promo_change integer,purchased_change integer,description text,reference_id uuid UNIQUE);`);
 await db.exec(await readFile(new URL('../paypal-webhook-migration.sql',import.meta.url),'utf8'));
 const q=async(sql,p)=>(await db.query(sql,p)).rows;
 const app=createApp({env:{APP_URL:'http://localhost:3000',SESSION_SECRET:'test-secret-more-than-thirty-two-characters',ADMIN_PASSWORD_HASH:passwordHash('test-password')},query:q});
 const uid='857e28fc-df67-4dd1-be2d-24bfaa952503',id='657e28fc-df67-4dd1-be2d-24bfaa952503';await q("INSERT INTO users VALUES($1,'paid@example.com','Paid listener')",[uid]);await q('INSERT INTO wallets(user_id) VALUES($1)',[uid]);await q("INSERT INTO credit_load_orders(id,user_id,amount_pesos,credits,payment_provider,payment_reference,status) VALUES($1,$2,100,105,'gcash','REAL-REF','pending')",[id,uid]);
 const admin=request.agent(app);const post=(path,body)=>admin.post(path).set('Origin','http://localhost:3000').send(body);const remove=()=>admin.delete('/api/admin/credit-loads/'+id).set('Origin','http://localhost:3000');
 assert.equal((await remove()).status,401);await post('/api/login',{password:'test-password'});
 assert.equal((await admin.get('/api/admin/credit-loads')).status,200);assert.equal((await remove()).status,503);
 await db.exec(await readFile(new URL('../credit-load-history-migration.sql',import.meta.url),'utf8'));
 assert.equal((await admin.delete('/api/admin/credit-loads/'+id).set('Origin','https://wrong.test')).status,403);
 assert.equal((await post('/api/admin/credit-loads/'+id+'/review',{status:'approved',verified:true})).status,200);
 const before=(await q('SELECT * FROM credit_load_orders WHERE id=$1',[id]))[0];
 assert.equal((await remove()).status,200);assert.equal((await remove()).status,200);
 const after=(await q('SELECT * FROM credit_load_orders WHERE id=$1',[id]))[0];assert.deepEqual({...after,admin_deleted_at:null},before);assert.ok(after.admin_deleted_at);
 assert.equal((await q('SELECT purchased_credits FROM wallets'))[0].purchased_credits,105);assert.equal((await q('SELECT * FROM credit_transactions')).length,1);
 const rows=(await admin.get('/api/admin/credit-loads')).body;assert.equal(rows.length,1);assert.equal(rows[0].status,'approved');assert.equal(rows[0].paymentReference,'REAL-REF');assert.ok(rows[0].deletedAt);
 assert.equal((await post('/api/admin/credit-loads/'+id+'/restore',{})).status,200);assert.equal((await admin.get('/api/admin/credit-loads')).body[0].deletedAt,null);
 assert.equal((await q('SELECT purchased_credits FROM wallets'))[0].purchased_credits,105);
});
