import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {createApp} from '../src/index.js';
import {passwordHash,digest} from '../src/security.js';
const require=createRequire(import.meta.url);const {PGlite}=require(process.env.MQ3_PGLITE_MODULE);
const origin='http://localhost:3000';const secret='test-secret-more-than-thirty-two-characters';
const link='https://suno.com/song/657e28fc-df67-4dd1-be2d-24bfaa952503';
const other='https://suno.com/song/756e28fc-df67-4dd1-be2d-24bfaa952504';
test('MP3 purchases debit once, track delivery and refund the original credit buckets',async t=>{
 const db=new PGlite();t.after(()=>db.close());await db.exec(await readFile(new URL('../schema.sql',import.meta.url),'utf8'));
 await db.exec(`CREATE TABLE users(id uuid PRIMARY KEY,email text,display_name text);
 CREATE TABLE user_sessions(token_hash text PRIMARY KEY,user_id uuid,expires_at timestamptz);
 CREATE TABLE wallets(user_id uuid PRIMARY KEY,promo_credits integer,purchased_credits integer,lifetime_gifted integer DEFAULT 0,updated_at timestamptz);
 CREATE TABLE gifts(id uuid PRIMARY KEY,user_id uuid,song_id uuid,gift_type text,credits integer,message text,created_at timestamptz DEFAULT now());
 CREATE TABLE credit_transactions(id uuid PRIMARY KEY,user_id uuid,transaction_type text,promo_change integer,purchased_change integer,description text,reference_id uuid);`);
 const q=async(sql,p)=>(await db.query(sql,p)).rows;
 const app=createApp({env:{APP_URL:origin,SESSION_SECRET:secret,ADMIN_PASSWORD_HASH:passwordHash('test-password')},query:q});
 const id='657e28fc-df67-4dd1-be2d-24bfaa952503',mp3='757e28fc-df67-4dd1-be2d-24bfaa952503',uid='857e28fc-df67-4dd1-be2d-24bfaa952503';
 await q("INSERT INTO songs(id,title,category,published,suno_url) VALUES($1,'Moses','NAME SONGS',true,$2)",[id,link]);
 await q("INSERT INTO songs(id,title,category,published,audio_path) VALUES($1,'Old song','OPM',true,'songs/old.mp3')",[mp3]);
 await q("INSERT INTO users VALUES($1,'test@example.com','Tester')",[uid]);await q('INSERT INTO wallets(user_id,promo_credits,purchased_credits) VALUES($1,25,50)',[uid]);
 await q("INSERT INTO user_sessions VALUES($1,$2,now()+interval '1 day')",[digest('test-session',secret),uid]);

 const post=(agent,path,body={})=>agent.post(path).set('Origin',origin).send(body);
 const buyer=request.agent(app);const buy=()=>buyer.post('/api/account/mp3-requests').set('Origin',origin).set('Cookie','mq3_user=test-session').send({songId:id,credits:1,email:'attacker@example.com'});
 assert.equal((await request(app).post('/api/account/mp3-requests').set('Origin',origin).send({songId:id})).status,401);
 assert.equal((await request(app).get('/api/admin/mp3-requests')).status,401);
 assert.equal((await buy()).status,400);
 assert.equal((await q('SELECT * FROM mp3_requests')).length,0);
 assert.equal((await q('SELECT promo_credits+purchased_credits AS balance FROM wallets'))[0].balance,75);
 await q('UPDATE songs SET suno_gifts_enabled=true,suno_download_confirmed_at=now() WHERE id=$1',[id]);
 const [first,second]=await Promise.all([buy(),buy()]);assert.equal(first.status,200);assert.equal(second.status,200);
 assert.equal(first.body.request.id,second.body.request.id);
 let wallet=(await q('SELECT * FROM wallets'))[0];assert.equal(wallet.promo_credits,0);assert.equal(wallet.purchased_credits,25);assert.equal(wallet.lifetime_gifted,0);
 assert.equal((await q('SELECT * FROM credit_transactions')).length,1);
 const paid=(await q('SELECT * FROM mp3_requests'))[0];assert.equal(paid.email,'test@example.com');assert.equal(paid.credits,50);
 const insufficient=await buyer.post('/api/account/mp3-requests').set('Origin',origin).set('Cookie','mq3_user=test-session').send({songId:mp3});assert.equal(insufficient.status,400);
 const history=await buyer.get('/api/account/mp3-requests').set('Cookie','mq3_user=test-session');assert.equal(history.body.requests.length,1);
 const admin=request.agent(app);await post(admin,'/api/login',{password:'test-password'});
 assert.equal((await admin.get('/api/admin/mp3-requests')).body.length,1);
 assert.equal((await admin.post(`/api/admin/mp3-requests/${paid.id}/refund`).send({})).status,403);
 assert.equal((await post(admin,`/api/admin/mp3-requests/${paid.id}/refund`)).status,200);
 assert.equal((await post(admin,`/api/admin/mp3-requests/${paid.id}/refund`)).status,409);
 wallet=(await q('SELECT * FROM wallets'))[0];assert.equal(wallet.promo_credits,25);assert.equal(wallet.purchased_credits,50);
 assert.equal((await buy()).body.alreadyRequested,true);assert.equal((await q('SELECT * FROM credit_transactions')).length,2);
 const other=await buyer.post('/api/account/mp3-requests').set('Origin',origin).set('Cookie','mq3_user=test-session').send({songId:mp3});assert.equal(other.status,200);
 assert.equal((await post(admin,`/api/admin/mp3-requests/${other.body.request.id}/sent`)).status,200);
 assert.equal((await post(admin,`/api/admin/mp3-requests/${other.body.request.id}/sent`)).status,200);
 assert.equal((await post(admin,`/api/admin/mp3-requests/${other.body.request.id}/refund`)).status,409);
 assert.equal((await q("SELECT * FROM mp3_requests WHERE status='sent'")).length,1);
});
