import test from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {createApp} from '../src/index.js';
import {passwordHash,digest} from '../src/security.js';
const require=createRequire(import.meta.url);const {PGlite}=require(process.env.MQ3_PGLITE_MODULE);
const origin='http://localhost:3000';const secret='test-secret-more-than-thirty-two-characters';
const link='https://suno.com/song/657e28fc-df67-4dd1-be2d-24bfaa952503';
const other='https://suno.com/song/756e28fc-df67-4dd1-be2d-24bfaa952504';
test('admin confirmed downloads control real gift debits, link changes reset approval',async t=>{
 const db=new PGlite();t.after(()=>db.close());await db.exec(await readFile(new URL('../schema.sql',import.meta.url),'utf8'));
 await db.exec(`CREATE TABLE users(id uuid PRIMARY KEY,email text,display_name text);
 CREATE TABLE user_sessions(token_hash text PRIMARY KEY,user_id uuid,expires_at timestamptz);
 CREATE TABLE wallets(user_id uuid PRIMARY KEY,promo_credits integer,purchased_credits integer,lifetime_gifted integer DEFAULT 0,updated_at timestamptz);
 CREATE TABLE gifts(id uuid PRIMARY KEY,user_id uuid,song_id uuid,gift_type text,credits integer,message text,created_at timestamptz DEFAULT now());
 CREATE TABLE credit_transactions(id uuid PRIMARY KEY,user_id uuid,transaction_type text,promo_change integer,purchased_change integer,description text,reference_id uuid);`);
 const q=async(sql,p)=>(await db.query(sql,p)).rows;
 const app=createApp({env:{APP_URL:origin,SESSION_SECRET:secret,ADMIN_PASSWORD_HASH:passwordHash('test-password')},query:q});
 const id='657e28fc-df67-4dd1-be2d-24bfaa952503',mp3='757e28fc-df67-4dd1-be2d-24bfaa952503',uid='857e28fc-df67-4dd1-be2d-24bfaa952503';
 await q("INSERT INTO songs(id,title,category,published,suno_url) VALUES($1,'Moses','NAME SONGS',true,$2)",[id,link]);
 await q("INSERT INTO songs(id,title,category,published,audio_path) VALUES($1,'Old song','OPM',true,'songs/old.mp3')",[mp3]);
 await q("INSERT INTO users VALUES($1,'test@example.com','Tester')",[uid]);await q('INSERT INTO wallets(user_id,promo_credits,purchased_credits) VALUES($1,25,50)',[uid]);
 await q("INSERT INTO user_sessions VALUES($1,$2,now()+interval '1 day')",[digest('test-session',secret),uid]);
 const admin=request.agent(app);const post=(path,body)=>admin.post(path).set('Origin',origin).send(body);
 const gift=(songId,extra={})=>request(app).post('/api/gifts/send').set('Origin',origin).set('Cookie','mq3_user=test-session').send({songId,giftType:'rose',...extra});
 const balance=async()=>Number((await q('SELECT promo_credits+purchased_credits AS balance FROM wallets'))[0].balance);
 const setting='/api/admin/songs/'+id+'/suno-gifts';
 const enable={downloadConfirmed:true,enabled:true,expectedSunoUrl:link};
 assert.equal((await post(setting,enable)).status,401);await post('/api/login',{password:'test-password'});
 assert.equal((await gift(id,{suno_gifts_enabled:true})).status,400);assert.equal(await balance(),75);
 assert.equal((await post(setting,{...enable,downloadConfirmed:false})).status,400);
 assert.equal((await post(setting,{...enable,expectedSunoUrl:other})).status,409);
 assert.equal((await post(setting,enable)).status,200);
 assert.equal((await request(app).get('/api/catalog')).body.songs.find(s=>s.id===id).gifts_enabled,true);
 assert.equal((await gift(id)).status,200);assert.equal(await balance(),70);assert.equal((await q('SELECT * FROM gifts')).length,1);assert.equal((await q('SELECT * FROM credit_transactions')).length,1);
 assert.equal((await post(setting,{...enable,enabled:false})).status,200);assert.equal((await gift(id)).status,400);assert.equal(await balance(),70);
 assert.ok((await q('SELECT suno_download_confirmed_at FROM songs WHERE id=$1',[id]))[0].suno_download_confirmed_at);
 assert.equal((await gift(mp3)).status,200);assert.equal(await balance(),65);
 await post(setting,enable);
 const edit={id,title:'Moses edited',category:'NAME SONGS',names:'Moses',lyrics:'Lyrics',price:0,published:true,suno_url:link};
 assert.equal((await post('/api/admin/songs',edit)).status,200);assert.equal((await q('SELECT suno_gifts_enabled FROM songs WHERE id=$1',[id]))[0].suno_gifts_enabled,true);
 assert.equal((await post('/api/admin/songs',{...edit,suno_url:other})).status,200);
 const changed=(await q('SELECT suno_gifts_enabled,suno_download_confirmed_at FROM songs WHERE id=$1',[id]))[0];assert.equal(changed.suno_gifts_enabled,false);assert.equal(changed.suno_download_confirmed_at,null);
 assert.equal((await gift(id)).status,400);assert.equal(await balance(),65);
 assert.equal((await post(setting,enable)).status,409);
});
