import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {chromium} from '@playwright/test';
import {createApp} from '../src/index.js';
import {testStore} from '../scripts/test-store.js';

const store=await testStore();
store.env.BLOB_READ_WRITE_TOKEN='local-test-only';
let uploads=0;const removed=[];
store.putCover=async()=>{uploads++;};store.deleteCover=async path=>removed.push(path);
const server=createApp(store).listen(0,'127.0.0.1');
await new Promise(resolve=>server.once('listening',resolve));
const origin='http://127.0.0.1:'+server.address().port;store.env.APP_URL=origin;
const id='00000000-0000-4000-8000-000000000001';
await store.query('INSERT INTO hub_songs(id,title,category,youtube_url,spotify_url,published) VALUES($1,$2,$3,$4,$5,true)',[id,'Alpha Song','OPM','https://www.youtube.com/watch?v=abcdefghijk','https://open.spotify.com/track/755cjxcwy9NvpinLWXngMC']);
await store.query('INSERT INTO hub_songs(id,title,category,youtube_url,published) VALUES($1,$2,$3,$4,true)',['00000000-0000-4000-8000-000000000002','Beta Song','Love Songs','https://www.youtube.com/watch?v=abcdefghijl']);
let browser;
try {
 browser=await chromium.launch({headless:true,channel:process.env.TEST_BROWSER_CHANNEL||'msedge'});
 const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
 await context.addInitScript(()=>Object.defineProperty(navigator,'share',{value:undefined,configurable:true}));
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const optionClick=async selector=>{if(!await page.locator('#player-options').getAttribute('open').then(x=>x!==null))await page.locator('#player-options > summary').click();await page.locator(selector).click();};
 // Keep regression tests deterministic; real external embeds are checked separately.
 await page.route('https://**/*',route=>route.fulfill({contentType:'text/html',body:'<html><body>Platform test frame</body></html>'}));
 await page.goto(origin);await page.locator('#song-title').filter({hasText:'Alpha Song'}).waitFor();
 await page.locator('#player iframe').evaluate(el=>{el.dataset.identity='original-player';});
 await page.locator('#search').fill('Beta');
 assert.equal(await page.locator('.song-row').count(),1);
 assert.equal(await page.locator('#song-title').textContent(),'Alpha Song');
 assert.equal(await page.locator('#player iframe').getAttribute('data-identity'),'original-player');
 await page.locator('#search').fill('');await page.locator('#spotify').click();
 assert.match(await page.locator('#player iframe').getAttribute('allow'),/encrypted-media/);
 assert.equal(await page.locator('#open-spotify').getAttribute('href'),'https://open.spotify.com/track/755cjxcwy9NvpinLWXngMC');
 await optionClick('#favorite-song');await optionClick('[data-collection="favorites"]');
 assert.equal(await page.locator('.song-row').count(),1);await page.reload();
 assert.equal(await page.locator('#favorite-song').getAttribute('aria-pressed'),'true');
 await optionClick('#share-song');await page.locator('#status').filter({hasText:'Song link copied.'}).waitFor();
 assert.match(await page.evaluate(()=>navigator.clipboard.readText()),new RegExp('song='+id));
 await optionClick('[data-collection="recent"]');assert.equal(await page.locator('.song-row').count(),1);
 await optionClick('#clear-recent');assert.equal(await page.locator('.song-row').count(),0);
 await optionClick('[data-collection="all"]');
 await page.locator('#player-options > summary').click();assert.equal(await page.locator('#favorite-song').isVisible(),false);
 await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/listener-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'test-results/listener-mobile.png',fullPage:true});
 console.log('PASS: search preserves player; favorites/recent/share; Spotify permission and fallback; mobile width.');

 await page.setViewportSize({width:1440,height:1000});await page.goto(origin+'/admin');
 await page.locator('[name=password]').fill('preview-only');await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.locator('#dashboard').waitFor();await page.locator('#new-song').click();
 await page.locator('[name=title]').fill('Draft Regression');await page.getByRole('button',{name:'Save song',exact:true}).click();
 const draftRow=page.locator('#song-rows tr').filter({hasText:'Draft Regression'});await draftRow.waitFor();
 assert.match(await draftRow.textContent(),/Draft \/ Unpublished/);
 await draftRow.getByRole('button',{name:'Edit',exact:true}).click();
 await page.locator('[name=youtube_url]').fill('https://youtu.be/abcdefghijk');await page.locator('[name=published]').check();
 await page.getByRole('button',{name:'Save song',exact:true}).click();await page.locator('#song-form').waitFor({state:'hidden'});
 await draftRow.locator('input').check();page.once('dialog',dialog=>dialog.accept());await page.locator('#remove-selected').click();
 await draftRow.getByRole('button',{name:'Publish / Restore'}).waitFor();
 await draftRow.getByRole('button',{name:'Publish / Restore'}).click();
 await page.waitForFunction(()=>[...document.querySelectorAll('#song-rows tr')].some(r=>r.textContent.includes('Draft Regression')&&r.textContent.includes('Published')));
 await page.locator('#library-filter').selectOption('drafts');assert.equal(await page.locator('#song-rows tr').filter({hasText:'Draft Regression'}).count(),0);
 await page.locator('#library-filter').selectOption('all');
 console.log('PASS: save draft, edit, publish, unpublish, restore and admin filters.');

 await page.locator('#new-song').click();await page.locator('[name=title]').fill('Cover Retry');
 await page.locator('#generate-cover').click();await page.locator('#cover-status').filter({hasText:'ready to save'}).waitFor();
 let rejectSave=true;
 await page.route('**/api/admin/songs',route=>route.request().method()==='POST'&&rejectSave?(rejectSave=false,route.fulfill({status:400,contentType:'application/json',body:'{"error":"Temporary validation failure"}'})):route.continue());
 await page.getByRole('button',{name:'Save song',exact:true}).click();await page.locator('#message').filter({hasText:'Temporary validation failure'}).waitFor();
 assert.equal(uploads,1);
 await page.getByRole('button',{name:'Save song',exact:true}).click();await page.locator('#song-form').waitFor({state:'hidden'});assert.equal(uploads,1);
 await page.locator('#new-song').click();await page.locator('[name=title]').fill('Cancel Upload');await page.locator('#generate-cover').click();
 await page.locator('#cover-status').filter({hasText:'ready to save'}).waitFor();rejectSave=true;
 await page.getByRole('button',{name:'Save song',exact:true}).click();await page.locator('#message').filter({hasText:'Temporary validation failure'}).waitFor();
 await page.locator('#cancel-song').click();await page.locator('#song-form').waitFor({state:'hidden'});assert.equal(removed.length,1);
 await page.screenshot({path:'test-results/admin-library.png',fullPage:true});
 console.log('PASS: failed save reuses uploaded cover; cancel removes unused upload.');

 await page.locator('[data-tab=analytics]').click();await page.locator('#total-views').filter({hasText:'1'}).waitFor();
 assert.equal((await store.query('SELECT * FROM hub_events')).length,1);
 await page.unroute('**/api/admin/songs');
 let catalogFail=true;await page.route('**/api/catalog',route=>catalogFail?(catalogFail=false,route.fulfill({status:503,contentType:'application/json',body:'{"error":"Try again"}'})):route.continue());
 await page.goto(origin);await page.locator('#retry-catalog').waitFor();await page.locator('#retry-catalog').click();await page.locator('.song-row').first().waitFor();
 assert.equal(await page.locator('#retry-catalog').isVisible(),false);
 assert.deepEqual(errors,[]);
 console.log('PASS: initial view counted once across reloads, analytics UI, catalog retry, no application JS errors.');
} finally {if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
